services:

  kafka:
    container_name: lab7-kafka
    image: soldevelo/kafka:3.9
    ports:
      - '9094:9094'
    networks:
      - airflow-kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    volumes:
      - ./kafka:/bitnami/kafka

  kafka-ui:
    container_name: lab7-kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8000:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: PLAINTEXT://kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
    networks:
      - airflow-kafka

  docker-proxy:
    container_name: lab7-docker-proxy
    image: alpine/socat
    command: "TCP4-LISTEN:2375,fork,reuseaddr UNIX-CONNECT:/var/run/docker.sock"
    ports:
      - "2376:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - airflow-kafka
  #  docker-socker-proxy:
  #    image: technativa/docker-socket-proxy:0.4
  #    environment:
  #      CONTAINERS: 1
  #      IMAGES: 1
  #      AUTH: 1
  #      POSt: 1
  #    privileged: true
  #    volumes:
  #      - /var/run/docker.sock:/var/run/docker.sock:ro
  #    restart: always
  #    networks:
  #      - airflow-kafka

  mock-api:
    container_name: lab7-mock-api
    build:
      context: ./mock-api
      dockerfile: Dockerfile
    image: rappel-conso/mock-api:0.1
    restart: always
    ports:
      - "8888:8888"
    networks:
      - airflow-kafka

networks:
  airflow-kafka:
    external: true
